"""Initial alembic script

Revision ID: 58fa1949e715
Revises:
Create Date: 2022-06-14 11:42:44.980780

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '58fa1949e715'
down_revision = None
branch_labels = None
depends_on = None

volumestatus = sa.Enum('New', 'Processing', 'Update', 'Db_done', 'Bucket_done', 'Done', 'Error', name='volumestatus')
pagecolor = sa.Enum('BW', 'Greyscale', 'Color', name='pagecolor')
pagetype = sa.Enum('Normal', 'FrontMatter', 'BackMatter', 'Insert', 'Plate', name='pagetype')
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_volume',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', volumestatus, nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal', 'volume')
    )
    op.create_index('volume_index', 'journal_volume', ['journal', 'volume'], unique=False)
    op.create_table('article',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('bibcode', sa.String(), nullable=True),
    sa.Column('journal_volume_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['journal_volume_id'], ['journal_volume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bibcode')
    )
    op.create_index('article_bibcode_index', 'article', ['bibcode'], unique=False)
    op.create_index('article_volume_index', 'article', ['journal_volume_id'], unique=False)
    op.create_table('page',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('color_type', pagecolor, nullable=True),
    sa.Column('page_type', pagetype, nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('journal_volume_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('volume_running_page_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_volume_id'], ['journal_volume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_volume_id', 'name'),
    sa.UniqueConstraint('journal_volume_id', 'volume_running_page_num')
    )
    op.create_index('page_name_index', 'page', ['name'], unique=False)
    op.create_index('page_volume_index', 'page', ['journal_volume_id'], unique=False)
    op.create_table('page2article',
    sa.Column('page_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('article_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page2article')
    op.drop_index('page_volume_index', table_name='page')
    op.drop_index('page_name_index', table_name='page')
    op.drop_table('page')
    op.drop_index('article_volume_index', table_name='article')
    op.drop_index('article_bibcode_index', table_name='article')
    op.drop_table('article')
    op.drop_index('volume_index', table_name='journal_volume')
    op.drop_table('journal_volume')
    volumestatus.drop(op.get_bind(), checkfirst=False)
    pagecolor.drop(op.get_bind(), checkfirst=False)
    pagetype.drop(op.get_bind(), checkfirst=False)

    # ### end Alembic commands ###
