"""Article_page_number

Revision ID: d7c87e120935
Revises: 58fa1949e715
Create Date: 2022-06-15 10:07:31.450466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c87e120935'
down_revision = '58fa1949e715'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('start_page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'start_page_number')
    # ### end Alembic commands ###
